### PR TITLE
:green_heart: Fixing Appveyor errors & :memo: Clean up template

### PR DESCRIPTION
**Pull request by irwindoug**
## Description
Appveyor is error-ing out on pull requests. This is to fix that.
Also, templates have unnecessary titles along the top. This removes that.

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [X] My code follows the code style of this project.
- [X] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by irwindoug** [comment]
Still has errors. Closing this until errors are fixed.

**Comment by irwindoug** [comment]
~~Looks good to me!~~
Sill having problems. Don't merge until resolved!

**Comment by irwindoug** [comment]
Pull request is ready! 🐛's have been crushed!

**Review by fsckthesystem — APPROVED** [review]
I approve

**Pull request merged**
